#!/bin/bash

kafka_dir="kafka_2.12-2.4.1/"

zookeeper_start=$kafka_dir"bin/zookeeper-server-start.sh "

zookeeper_stop=$kafka_dir"bin/zookeeper-server-stop.sh "

zookeeper_config=$kafka_dir"config/zookeeper.properties"

broker_command=$kafka_dir"bin/kafka-server-start.sh "

broker_config="server_properties/"

number_of_brokers=8

if [ $# -eq 1 ]
then
    while getopts scd option
    do
        case "${option}"
        in
        s) kafka_2.12-2.4.1/bin/zookeeper-server-start.sh kafka_2.12-2.4.1/config/zookeeper.properties >logs/zookeeper.out 2>&1 &
           sleep 5
           printf "Zookeeper started!\n"
           for (( i=1; i<=$number_of_brokers; i++ )) 
      	   do
              eval $broker_command$broker_config"server"$i".properties" >logs/broker"$i".out 2>&1 &
      		    sleep 5
              printf "Broker "$i" started!\n"
      	   done
           ;;
        c) kafka_2.12-2.4.1/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 3 --partitions 3 --topic BatchTopic --config min.insync.replicas=2 --config unclean.leader.election.enable=false >logs/batchTopic.out 2>&1
           sleep 2
           printf "Kafka batch topic created!\n"
           kafka_2.12-2.4.1/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 3 --partitions 3 --topic ReportTopic --config min.insync.replicas=2 --config unclean.leader.election.enable=false >logs/reportTopic.out 2>&1
           sleep 2
           printf "Kafka report topic created!\n"
           kafka_2.12-2.4.1/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 3 --partitions 3 --topic AlarmTopic  --config min.insync.replicas=2 --config unclean.leader.election.enable=false >logs/alarmTopic.out 2>&1
           sleep 2
           printf "Kafka alarm topic created!\n"
           ;;
        d) kafka_2.12-2.4.1/bin/kafka-server-stop.sh >logs/brokers-terminate.out 2>&1
           sleep 30
           printf "Kafka nodes terminated!\n"
           kafka_2.12-2.4.1/bin/zookeeper-server-stop.sh >logs/zookeeper-terminate.out 2>&1
           sleep 2
           printf "Zookeeper terminated!\n"
           ;;
        *) printf "Command usage: ./kafka   -s to initialize\n\t\t\t -c to create the topics\n\t\t\t -d to disconnect\n"
           ;;
        esac
    done
else
    printf "Command usage: ./kafka   -s to initialize\n\t\t\t -c to create the topics\n\t\t\t -d to disconnect\n"
fi
